### ISSUE TITLE
If you stay in fullscreen, this green line appears in the crosshairs

### ISSUE THREAD

**Issue by seriousfreezing** [JustAlittleWolf/centered-crosshair#3]
![image](https://github.com/JustAlittleWolf/centered-crosshair/assets/66693072/e15316a3-5e83-40d9-8746-1d3977b47012)

If you want to reproduce it, just use the smaller VanillaTweaks crosshair and set it to fullscreen

**Comment by JustAlittleWolf** [comment]
Hello, thanks for the issue! Unfortunately I wasn't able to reproduce it, I tried using the small crosshair like you suggested but it works fine for me. Could you specify which version of the mod you are using and your screen resolution? This could also be an issue with using shaders or an incompatibility with another mod.

**Comment by seriousfreezing** [comment]
Yep. It's fixed by removing this mod.

**Comment by JustAlittleWolf** [comment]
Does the issue also happen when you have only centered-crosshairs installed? If so could you send a screenshot of your mods folder with the mods you are using?

**Comment by seriousfreezing** [comment]
![image](https://github.com/JustAlittleWolf/centered-crosshair/assets/66693072/2d8558cd-7541-4941-b0ea-7c243169b11d)

**Comment by JustAlittleWolf** [comment]
Hi, I found the problem. Modernfix has a patch called `mixin.perf.faster_texture_stitching` and somehow that messes up some of the calculations within centered-crosshairs. In the newest release `1.0.6` I've addressed this issue and modified the calculation so the issue no longer happens.
Thanks for bringing this issue to my attention!
