### ISSUE TITLE
Crashes when using 1.20.4

### ISSUE THREAD

**Issue by Xrey274** [JustAlittleWolf/centered-crosshair#4]

**Comment by JustAlittleWolf** [comment]
Hello, it seems to be working fine for me.
![image](https://github.com/JustAlittleWolf/centered-crosshair/assets/54244277/1691212b-2270-4826-b169-85612c7c298f)
Which version are you using and could you send your latest.log file?

**Comment by Xrey274** [comment]
I saw what the problem is. In moderinth you've made the featured version 1.0.0, not 1.0.6 and I thought that was the latest. Sorry for the mistake.

**Comment by JustAlittleWolf** [comment]
Oh, I wasn't aware that was a thing. Thanks for bringing it to my attention, it should be fixed now!
